{
 "title": "Go RED",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(up{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(up{namespace=\"$namespace\", service=\"$service\"}, pod)"
   },
   {
    "name": "metric",
    "query": "{__name__=~\".+\",pod=~\"${pod:regex}\",namespace=\"$namespace\"}"
   }
  ]
 },
 "panels": [
  { "title": "$metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "metric" },
  {
   "title": "Rate $metric",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ( rate([[metric]]_total{namespace=\"$namespace\", service=\"$service\"} [1m] ))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum  by (le) (rate(amqp_send_duration_seconds_bucket{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (\n  (sum ( rate([[metric]]_total{namespace=\"$namespace\", service=\"$service\", error=\"\"} [1m] ))) / \n  (sum ( rate([[metric]]_total{namespace=\"$namespace\", service=\"$service\"} [1m] )))\n)"
    }
   ]
  },
  { "title": "Deep dive [[pod]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "pod" },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)"
    }
   ]
  },
  {
   "title": "P99",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "legendFormat": "p99 {{ __name__ }}" }
   ]
  },
  {
   "title": "P90",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"[[metric:regex]].*duration_seconds\",namespace=\"$namespace\", pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "p90 {{ __name__ }}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)"
    }
   ]
  },
  {
   "title": "GC count 1m",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{namespace=\"$namespace\", pod=\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "[[metric]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "repeat": "metric",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "[[metric]]_approx_duration_seconds{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "percentile {{quantile}}"
    }
   ]
  },
  { "title": "Deep dive [[pod]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)"
    }
   ]
  },
  {
   "title": "P99",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "legendFormat": "p99 {{ __name__ }}" }
   ]
  },
  {
   "title": "P90",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"[[metric:regex]].*duration_seconds\",namespace=\"$namespace\", pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "p90 {{ __name__ }}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 33 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)"
    }
   ]
  },
  {
   "title": "GC count 1m",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{namespace=\"$namespace\", pod=\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "[[metric]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "repeat": "metric",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "[[metric]]_approx_duration_seconds{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "percentile {{quantile}}"
    }
   ]
  }
 ]
}